# SuperBench Config for GB300 Single-Node Benchmarking
# Optimized for NVIDIA Blackwell GPUs on Azure GB300
version: v0.12

superbench:
  enable: null
  monitor:
    enable: false  # Disable monitor to avoid issues
  var:
    common_model_config: &common_model_config
      duration: 0
      num_warmup: 2
      num_steps: 10
      batch_size: 32
      precision:
        - float32
      model_action:
        - train

  benchmarks:
    # GPU Computation - GEMM (General Matrix Multiply)
    gemm-flops:
      enable: true
      modes:
        - name: local
          proc_num: 1
          parallel: no
      parameters:
        precision:
          - fp32
          - fp16
        duration: 10
        n: 8192
        m: 8192
        k: 8192

    # NCCL Bandwidth (GPU communication)
    nccl-bw:
      enable: true
      modes:
        - name: local
          proc_num: 4
          parallel: yes
      parameters:
        operation: allreduce
        minbytes: 1
        maxbytes: 1G
        ngpus: 1

    # Simple PyTorch benchmark - ResNet50
    pytorch-resnet50:
      enable: true
      modes:
        - name: local
          proc_num: 1
          parallel: no
      parameters:
        <<: *common_model_config
        batch_size: 64
        duration: 0
        num_warmup: 1
        num_steps: 5


