# SuperBench Config for GB300 Single-Node Benchmarking
# Optimized for NVIDIA Blackwell GPUs on Azure GB300
version: v0.12

superbench:
  enable: null
  monitor:
    enable: false  # Disable monitor to avoid issues
  var:
    common_model_config: &common_model_config
      duration: 0
      num_warmup: 1
      num_steps: 5
      batch_size: 32
      precision:
        - float32
      model_action:
        - train

  benchmarks:
    # GPU Computation - GEMM using CUTLASS profiler
    gemm-flops:
      enable: true
      modes:
        - name: local
          proc_num: 1
          parallel: no
      parameters:
        precision:
          - fp32
          - fp16
        duration: 5
        n: 4096
        m: 4096
        k: 4096

    # Simple PyTorch benchmark - ResNet50
    pytorch-resnet50:
      enable: true
      modes:
        - name: local
          proc_num: 1
          parallel: no
      parameters:
        <<: *common_model_config
        batch_size: 64
        duration: 0
        num_warmup: 1
        num_steps: 3

    # Simple PyTorch benchmark - BERT Base
    pytorch-bert-base:
      enable: true
      modes:
        - name: local
          proc_num: 1
          parallel: no
      parameters:
        <<: *common_model_config
        batch_size: 16
        duration: 0
        num_warmup: 1
        num_steps: 3



